<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AudioLimits.App</RootNamespace>
    <AssemblyName>AudioLimits.App</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AudioLimits.ico</ApplicationIcon>
    <Product>Audio Limits</Product>
    <AssemblyTitle>Audio Limits</AssemblyTitle>
    <Description>Audio Limits WinUI application</Description>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>1.0.0-rc.2</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <RepositoryUrl>https://github.com/MicaLovesKPOP/AudioLimits</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioLimits.Core\AudioLimits.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\AudioLimits-AppIcon-32.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\AudioLimits.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\*.svg" />
  </ItemGroup>
</Project>
